# Generated by Django 6.0.4 on 2026-08-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (URL)')),
                ('type', models.CharField(choices=[('product', 'Boutique (Produits)'), ('service', 'Services Entreprise'), ('realization', 'Réalisations & Projets')], default='product', max_length=20, verbose_name='Type de contenu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, default='folder', help_text="Nom de l'icône Lucide (ex: cpu, shield, server, shopping-bag)", max_length=50)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('service_interest', models.CharField(blank=True, max_length=100, verbose_name='Service concerné')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu / Traité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de Contact',
                'verbose_name_plural': 'Messages de Contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=50, unique=True, verbose_name='Numéro de Commande')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Nom complet du client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('customer_phone', models.CharField(max_length=30, verbose_name='Numéro de téléphone')),
                ('delivery_address', models.TextField(verbose_name='Adresse de livraison')),
                ('city', models.CharField(default='Abidjan / Paris', max_length=100, verbose_name='Ville')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant total')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('shipped', 'Expédiée / En livraison'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut de la commande')),
                ('notes', models.TextField(blank=True, verbose_name='Notes / Instructions de livraison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (URL)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (FCFA / EUR)')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix réduit (Optionnel)')),
                ('short_description', models.TextField(verbose_name='Courte description')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète & Spécifications')),
                ('stock', models.IntegerField(default=10, verbose_name='Quantité en stock')),
                ('badge', models.CharField(blank=True, help_text='ex: Nouveau, Promo, Top Ventes, Recommandé', max_length=50, verbose_name='Badge / Label')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='Note sur 5')),
                ('reviews_count', models.IntegerField(default=12, verbose_name="Nombre d'avis")),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name="URL de l'image du produit")),
                ('specs', models.TextField(blank=True, help_text='Spécifications (ex: Garantie: 2 ans\\nMarque: STANTECH)', verbose_name='Fiche technique (Clé: Valeur par ligne)')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Produit Vedette (En avant)')),
                ('is_active', models.BooleanField(default=True, verbose_name='En vente / Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'product'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit (Boutique)',
                'verbose_name_plural': 'Produits (Boutique)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantité')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sous-total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Commande')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='Realization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du projet / Réalisation')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (URL)')),
                ('client_name', models.CharField(blank=True, max_length=150, verbose_name='Nom du client')),
                ('short_description', models.TextField(verbose_name='Résumé court')),
                ('full_description', models.TextField(blank=True, verbose_name='Description détaillée')),
                ('tech_stack', models.CharField(blank=True, max_length=255, verbose_name='Technologies utilisées (séparées par des virgules)')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name="URL de l'image de présentation")),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Date de livraison')),
                ('project_url', models.URLField(blank=True, verbose_name='Lien externe du projet')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en vedette (Accueil)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'realization'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name="Domaine d'intervention")),
            ],
            options={
                'verbose_name': 'Réalisation',
                'verbose_name_plural': 'Réalisations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du Service')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (URL)')),
                ('icon', models.CharField(default='cpu', help_text='Icône Lucide (ex: cpu, shield, code, database, cloud, settings)', max_length=50)),
                ('short_description', models.TextField(verbose_name='Résumé court')),
                ('full_description', models.TextField(blank=True, verbose_name='Description complète')),
                ('features', models.TextField(blank=True, help_text='Une fonctionnalité par ligne', verbose_name='Points clés / Inclus')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name="URL ou chemin de l'image")),
                ('is_featured', models.BooleanField(default=False, verbose_name="Mettre en avant (Page d'accueil)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'service'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
