# Generated by Django 6.0.4 on 2026-08-21 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('product', 'Boutique (Produits)'), ('service', 'Services Entreprise'), ('realization', 'Réalisations & Projets'), ('application', 'Applications & SaaS')], default='product', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Nom de l'application")),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug (URL)')),
                ('platform', models.CharField(choices=[('web', 'Web App'), ('mobile', 'Application Mobile (iOS / Android)'), ('desktop', 'Application Desktop'), ('saas', 'Plateforme SaaS'), ('ai', 'Solution IA & Data')], default='web', max_length=20, verbose_name='Plateforme / Format')),
                ('version', models.CharField(blank=True, default='v1.0.0', max_length=30, verbose_name='Version')),
                ('icon', models.CharField(default='layout', help_text="Nom de l'icône Lucide (ex: layout, smartphone, monitor, cloud, cpu, box, shield, code)", max_length=50, verbose_name='Icône Lucide')),
                ('short_description', models.TextField(verbose_name='Résumé court')),
                ('full_description', models.TextField(blank=True, verbose_name='Description détaillée & Fonctionnalités')),
                ('tech_stack', models.CharField(blank=True, help_text='Séparées par des virgules (ex: Python, Django, React, Flutter, PostgreSQL)', max_length=255, verbose_name='Stack Technique')),
                ('image_url', models.CharField(blank=True, max_length=500, verbose_name="URL de l'image / Screenshot")),
                ('demo_url', models.URLField(blank=True, verbose_name='Lien Démo / Accès Web')),
                ('download_url', models.URLField(blank=True, verbose_name='Lien de Téléchargement / App Store')),
                ('badge', models.CharField(blank=True, help_text='ex: En Production, Beta, SaaS Multi-Tenant, Gratuit', max_length=50, verbose_name='Badge / Tag')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mettre en avant (Accueil)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif / Publié')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'type': 'application'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
