# Generated by Django 5.2.17 on 2026-10-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_type_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_badge',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Badge du produit'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_category',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Catégorie du produit'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Image du produit'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_short_description',
            field=models.TextField(blank=True, default='', verbose_name='Description courte'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_specs',
            field=models.TextField(blank=True, default='', verbose_name='Spécifications du produit'),
        ),
    ]
